### ISSUE TITLE
Please add a `blocked` label as well to all the repos

### ISSUE THREAD

**Issue by diasdavid** [ipfs/wg-qa-testing-dx#34]
@VictorBjelkholm could you please add a `blocked` label to all the repos as it was requested during the js-ipfs weekly -- https://github.com/ipfs/js-ipfs/issues/1179#issuecomment-376053929?

<img width="753" alt="image" src="https://user-images.githubusercontent.com/1211152/37926594-8efa4afc-30ec-11e8-8cd3-366132decca9.png">

**Comment by diasdavid** [comment]
Any hopes of getting this done soon?

**Comment by VictorBjelkholm** [comment]
Running this now. It's taking ~1 second per repository so expect it to be synced everywhere in ~10 minutes.
